# docker-compose.yml

version: '3'
services:
  realtime:
    image: supabase/realtime
    ports:
      - "4000:4000"
    environment:
      DB_HOST: db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
      PORT: 4000
      SECURE_CHANNELS: 'false'
    depends_on:
      - db
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    volumes:
    - ./db:/docker-entrypoint-initdb.d/
    command:
    - postgres
    - -c
    - wal_level=logical
    environment: 
      POSTGRES_PASSWORD: postgres
