---
- hosts: all
  become: true

  vars:
    realtime_version: 0.7.5
    realtime_checksum: sha1:64fec17e9c4ad27b0c9f0acb6a1e789e604ec56e

  tasks:
    - include_tasks: tasks/setup-system.yml

    - include_tasks: tasks/setup-realtime.yml

    - name: Remove temp dir at $HOME
      shell: rm -rf ~/.ansible
